/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteWorkflowArgs } from "./DeleteWorkflowArgs";
import { WorkflowFindManyArgs } from "./WorkflowFindManyArgs";
import { WorkflowFindUniqueArgs } from "./WorkflowFindUniqueArgs";
import { Workflow } from "./Workflow";
import { WorkflowService } from "../workflow.service";

@graphql.Resolver(() => Workflow)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class WorkflowResolverBase {
  constructor(
    protected readonly service: WorkflowService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Workflow",
    action: "read",
    possession: "any",
  })
  async _workflowsMeta(
    @graphql.Args() args: WorkflowFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Workflow])
  @nestAccessControl.UseRoles({
    resource: "Workflow",
    action: "read",
    possession: "any",
  })
  async workflows(
    @graphql.Args() args: WorkflowFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Workflow[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Workflow",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Workflow, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Workflow",
    action: "read",
    possession: "own",
  })
  async workflow(
    @graphql.Args() args: WorkflowFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Workflow | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Workflow",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Workflow)
  @nestAccessControl.UseRoles({
    resource: "Workflow",
    action: "delete",
    possession: "any",
  })
  async deleteWorkflow(
    @graphql.Args() args: DeleteWorkflowArgs
  ): Promise<Workflow | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
