/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteLoginArgs } from "./DeleteLoginArgs";
import { LoginFindManyArgs } from "./LoginFindManyArgs";
import { LoginFindUniqueArgs } from "./LoginFindUniqueArgs";
import { Login } from "./Login";
import { LoginService } from "../login.service";

@graphql.Resolver(() => Login)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class LoginResolverBase {
  constructor(
    protected readonly service: LoginService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "read",
    possession: "any",
  })
  async _loginsMeta(
    @graphql.Args() args: LoginFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Login])
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "read",
    possession: "any",
  })
  async logins(
    @graphql.Args() args: LoginFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Login[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Login",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Login, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "read",
    possession: "own",
  })
  async login(
    @graphql.Args() args: LoginFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Login | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Login",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Login)
  @nestAccessControl.UseRoles({
    resource: "Login",
    action: "delete",
    possession: "any",
  })
  async deleteLogin(
    @graphql.Args() args: DeleteLoginArgs
  ): Promise<Login | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
